// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnhAaOzYTN6Ii52sl1FgkZN7IzHv4n7tY',
    appId: '1:390125420903:web:6e90f17fdbc78016d22fc2',
    messagingSenderId: '390125420903',
    projectId: 'bmsce-ams',
    authDomain: 'bmsce-ams.firebaseapp.com',
    storageBucket: 'bmsce-ams.firebasestorage.app',
    measurementId: 'G-JR03894Z7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIBbYPityMSxo8VHc0A37NIh_8koSiVZ8',
    appId: '1:390125420903:android:9ee53231457e3e8cd22fc2',
    messagingSenderId: '390125420903',
    projectId: 'bmsce-ams',
    storageBucket: 'bmsce-ams.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrCByqMFyD5Qe9EKkmBjlByY2VloD0FVE',
    appId: '1:390125420903:ios:09e4539a56c7fb86d22fc2',
    messagingSenderId: '390125420903',
    projectId: 'bmsce-ams',
    storageBucket: 'bmsce-ams.firebasestorage.app',
    iosBundleId: 'com.example.amsBmsce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrCByqMFyD5Qe9EKkmBjlByY2VloD0FVE',
    appId: '1:390125420903:ios:09e4539a56c7fb86d22fc2',
    messagingSenderId: '390125420903',
    projectId: 'bmsce-ams',
    storageBucket: 'bmsce-ams.firebasestorage.app',
    iosBundleId: 'com.example.amsBmsce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnhAaOzYTN6Ii52sl1FgkZN7IzHv4n7tY',
    appId: '1:390125420903:web:9ea276aff6e681d2d22fc2',
    messagingSenderId: '390125420903',
    projectId: 'bmsce-ams',
    authDomain: 'bmsce-ams.firebaseapp.com',
    storageBucket: 'bmsce-ams.firebasestorage.app',
    measurementId: 'G-2BFMQQHJ2Z',
  );
}
